# Done to increase the memory available to gradle.
# Kotlin + Loom 编译/数据生成较吃内存
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.18.4
loom_version=1.15-SNAPSHOT
fabric_kotlin_version=1.13.9+kotlin.2.3.10

# Mod Properties
mod_version=0.5.2
maven_group=com.mcdebug
archives_base_name=mcdebug

# Dependencies
fabric_api_version=0.92.7+1.20.1
kotlin_version=2.3.10
